### ISSUE TITLE
nan loss

### ISSUE THREAD

**Issue by steveazzolin** [MANGA-UOFA/PTfer#1]
Dear author,

I was running your code for transferring prompts from bert-base-cased and roberta-base, but the resulting test precision is 0.0000 for both P17, P1001, and P101.
I noticed that during training it happens to see a NaN loss, but I can't figure out the reason. I did not change anything about your code, and I'm using the same package versions as yours on CPU (Python 3.8.18).

As a reference, the Macro accuracies of the prompts on their respective models are aligned with the ones in the Optiprompt paper (50.01 for bert, and 46.36 for roberta).

This is the output in the log file:

```

Namespace(absolute=False, all_anchors=False, budget=2000, common_vocab='/home/[...]/common_vocabs/common_vocab_cased.txt', data_path='/home/[...]/data/autoprompt_data', init_manual_template=False, log_path='./output/bert_base2roberta_base_log', log_tag='', lr=0.005, num_anchor=8192, num_vectors=5, prompt_filename='prompt_vecs.npy', relation='P1001', relation_profile='OptiPrompt/relation_metainfo/LAMA_relations.jsonl', seed=42, src_model='bert-base-cased', src_prompt_path='/home/[...]/optiprompt-outputs/bert-base-cased_cmp_lms_data/6', tgt_model='roberta-base', tgt_prompt_path='OptiPrompt/optiprompt-outputs/bert-large-cased', topk=8192, transferred_prompt_filename='transfered_prompt_vecs.npy')
Start searching for prompt embeddings for relation P1001
Relative representations stat: mean 0.0000, std 0.0000
Get best precision: 0.0000 at step 50! loss: 0.0000
Test precision: 0.0000

```

![image](https://github.com/MANGA-UOFA/PTfer/assets/53196079/b12d0799-f9aa-42e6-a341-9b3e5f23afe7)

Do you have an idea of why this happens?
Thanks for your support,
Steve

**Comment by khalilbalaree** [comment]
Hi, I noticed that the encoded relative embeddings of the prompt has mean and std both equal to zeros, this is the main reason of your issue. 

You can try to set —all_anchors to True and —topk to 8192 following our default settings.

**Comment by steveazzolin** [comment]
Sorry for the late response.
I tried following your suggestions but I still get the same:


```

Namespace(absolute=False, all_anchors=True, budget=2000, common_vocab='[...]/common_vocabs/common_vocab_cased.txt', data_path='[...]/data/autoprompt_data', init_manual_template=False, log_path='./output/bert_base2roberta_base_log', log_tag='', lr=0.005, num_anchor=8192, num_vectors=5, prompt_filename='prompt_vecs.npy', relation='P101', relation_profile='OptiPrompt/relation_metainfo/LAMA_relations.jsonl', seed=42, src_model='bert-base-cased', src_prompt_path=[...]/optiprompt-outputs/bert-base-cased_cmp_lms_data/6', tgt_model='roberta-base', tgt_prompt_path='OptiPrompt/optiprompt-outputs/bert-large-cased', topk=8192, transferred_prompt_filename='transfered_prompt_vecs.npy')

Start searching for prompt embeddings for relation P101
Relative representations stat: mean 0.0000, std 0.0000
Get best precision: 0.0000 at step 50! loss: 0.0000
Test precision: 0.0000

```


Thanks for your help!

**Comment by khalilbalaree** [comment]
It still gives you "Relative representations stat: mean 0.0000, std 0.0000". In get_emb.py, could you manually check the values from v_base and bert_base_anchors to see if any of them are all-zero tensors?
`decoder = Rel2abs_Decoder(args, logger, v_base, bert_base_anchors, bert_large_anchors, tgt_distribution)`
