### ISSUE TITLE
 reproducibility issue

### ISSUE THREAD

**Issue by MinwooPark96** [MANGA-UOFA/PTfer#3]
Hello,

I am writing to you with a question regarding your paper “Zero-Shot Continuous Prompt Transfer: Generalizing Task Semantics Across Language Models”.

I have a query about the reproducibility of performance on the SST-2 dataset. After training a soft prompt of length 5 on the bert-base-cased model, I used your code to perform inference on the roberta-large model but was unable to achieve any transferability. The prompt was trained using [mask, v1~v5, sentence] as the input. I would like to inquire about the specific experimental settings detailed in Appendix B of the paper.

**Comment by khalilbalaree** [comment]
Hi, you can try limiting the vocabs with only the label tokens (for example, "good" for the positive and "bad" for the negative classes in SST2). Another way is to define label tokens for each class, as described in the section "Automating Label Token Selection" from the autoprompt paper. Hope this can help, thanks!
