### ISSUE TITLE
AppendixB reproducibility issue

### ISSUE THREAD

**Issue by cjaep** [MANGA-UOFA/PTfer#4]
I would like to thank for your interesting paper and the provided code. They have been incredibly insightful and valuable for my work. 
However, I have a few questions regarding the implementation details in Appendix B (SST-2) that I hope you could clarify:
1) It appears that instead of using tokens for the entire vocabulary as anchor tokens, you used tokens related to each class. Could you please specify how many anchor tokens were utilized for each class?
2) When training the prompts for source model, how many labels did you use? Specifically, did you use all the tokens employed as anchor tokens in (1) as labels for training?
3) For the SST-2 dataset, what value did you set for top-k?
4) For the SST-2 dataset, what was the prompt length setting?

**Comment by khalilbalaree** [comment]
Thank you for your interest in our paper and for using the provided code. Regarding the your questions:
1&2. We still used the entire vocabulary for training the source model, and serves as the anchor tokens for transfer. Nevertheless, we limited the model's predictions to class label tokens, for example, "good" and "bad" in SST-2.
3. Top-k Value for SST-2:
When class labels are "good" and "bad", the top-k value is set to 2, which ensure that the target model focused on predicting the class labels.
4. Prompt Length Setting for SST-2:
The prompt length for the SST-2 dataset was set to 5, which is the same as our main experiments.
